name: CI-CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Download repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Inject .NET 4.0 Reference Assemblies
      run: |
        $xml = "<Project><ItemGroup><PackageReference Include='Microsoft.NETFramework.ReferenceAssemblies' Version='1.0.3' PrivateAssets='All' /></ItemGroup></Project>"
        Out-File -FilePath Directory.Build.props -InputObject $xml -Encoding UTF8
      shell: pwsh

    - name: Restore NuGet packages
      run: nuget restore Crowbar.sln

    - name: Compile
      run: msbuild Crowbar.sln /p:Configuration=Release /p:Platform=x86

    - name: Compress with 7z
      run: |
        $releaseDir = Get-ChildItem -Path . -Recurse -Directory -Filter "Release" | Where-Object { $_.FullName -like "*bin\x86\Release" } | Select-Object -First 1
        cd $releaseDir.FullName
        7z a "$($env:GITHUB_WORKSPACE)\Crowbar_darkmode.7z" Crowbar.exe

      shell: pwsh

    - name: Upload artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "v0.74_(DarkMode)" 
        name: "Crowbar_0.74(DarkMode)"
        draft: false
        prerelease: false
        files: Crowbar_darkmode.7z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
